In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('data/Inpatient_Psychiatric_Facility_Quality_Measure_Data___by_Facility.csv')
df.head()

,Provider_Number,Hospital_Name,Address,City,State,ZIP_Code,County_Name,HBIPS-2_Measure_Description,HBIPS-2_Overall_Rate_Per_1000,HBIPS-2_Overall_Num,...,IMM-2_Numerator,IMM-2_Denominator,IMM-2_Footnote,HCP_Measure_Description,HCP_%,HCP_Numerator,HCP_Denominator,HCP_Footnote,Flu_Season_Start_Date,Flu_Season_End_Date
0,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN STREET PO BOX 1010,OPP,AL,36467,Covington,Hours of physical-restraint use,0.00,0.00,...,50,128,NaN,Healthcare Personnel Influenza Vaccination,54,15,28,NaN,10/01/2015,03/31/2016
1,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,Crenshaw,Hours of physical-restraint use,0.44,59.63,...,88,88,NaN,Healthcare Personnel Influenza Vaccination,34,15,44,NaN,10/01/2015,03/31/2016
2,10011,ST. VINCENT'S EAST,50 MEDICAL PARK EAST DRIVE,BIRMINGHAM,AL,35235,Jefferson,Hours of physical-restraint use,0.00,0.00,...,54,80,NaN,Healthcare Personnel Influenza Vaccination,42,14,33,NaN,10/01/2015,03/31/2016
3,10012,DEKALB REGIONAL MEDICAL CENTER,200 MED CENTER DRIVE,FORT PAYNE,AL,35968,DeKalb,Hours of physical-restraint use,0.00,0.00,...,105,106,NaN,Healthcare Personnel Influenza Vaccination,100,54,54,NaN,10/01/2015,03/31/2016
4,10016,SHELBY BAPTIST MEDICAL CENTER,1000 FIRST STREET NORTH,ALABASTER,AL,35007,Shelby,Hours of physical-restraint use,0.11,41.02,...,171,171,NaN,Healthcare Personnel Influenza Vaccination,71,65,92,NaN,10/01/2015,03/31/2016

In [11]:
columns=df.columns
keep_cols=[]
for each_col in columns: 
    if not 'Description' in each_col: 
        keep_cols.append(each_col)
clean_df=df.loc[:, keep_cols] # df.loc[:, [col1, col2, col3]]

In [12]:
clean_df.dropna()

Empty DataFrame
Columns: [Provider_Number, Hospital_Name, Address, City, State, ZIP_Code, County_Name, HBIPS-2_Overall_Rate_Per_1000, HBIPS-2_Overall_Num, HBIPS-2_Overall_Den, HBIPS-2_Overall_Footnote, HBIPS-3_Overall_Rate_Per_1000, HBIPS-3_Overall_Num, HBIPS-3_Overall_Den, HBIPS-3_Overall_Footnote, HBIPS-5_Overall_%_of_Total, HBIPS-5_Overall_Num, HBIPS-5_Overall_Den, HBIPS-5_Overall_Footnote, HBIPS-6_Overall_%_of_Total, HBIPS-6_Overall_Num, HBIPS-6_Overall_Den, HBIPS-6_Overall_Footnote, HBIPS-7_Overall_%_of_Total, HBIPS-7_Overall_Num, HBIPS-7_Overall_Den, HBIPS-7_Overall_Footnote, SUB-1_%, SUB-1_Numerator, SUB-1_Denominator, SUB-1_Footnote, TOB-1_%, TOB-1_Numerator, TOB-1_Denominator, TOB-1_Footnote, TOB-2/-2a_Measure_Desc, TOB-2_%, TOB-2_Numerator, TOB-2/-2a_Denominator, TOB-2_Footnote, TOB-2a_%, TOB-2a_Numerator, TOB-2/-2a__Denominator, TOB-2a_Footnote, PEoC_Assessed_Response, PEoC_Assessed_Footnote, EHR_Use_Response, EHR_Use_Footnote, HIE_Response, HIE_Footnote, Start_Date, End_Date, FUH-30_%, FUH-30_Numerator, FUH-30_Denominator, FUH-30_Footnote, FUH-7_%, FUH-7_Numerator, FUH-7_Denominator, FUH-7_Footnote, FUH_Measure_Start_Date, FUH_Measure_End_Date, IMM-2_%, IMM-2_Numerator, IMM-2_Denominator, IMM-2_Footnote, HCP_%, HCP_Numerator, HCP_Denominator, HCP_Footnote, Flu_Season_Start_Date, Flu_Season_End_Date]
Index: []

[0 rows x 72 columns]

In [13]:
clean_df.dtypes

Provider_Number            int64
Hospital_Name             object
Address                   object
City                      object
State                     object
                          ...
HCP_Numerator             object
HCP_Denominator           object
HCP_Footnote             float64
Flu_Season_Start_Date     object
Flu_Season_End_Date       object
Length: 72, dtype: object

In [35]:
for idx, row in clean_df.iterrows(): 
    for sidx, cell in row.iteritems(): 
        clean_df.loc[idx, sidx]=str(cell).replace('%', '')

In [38]:
clean_df.to_csv('data/clean_data.csv', index=False)